image: node:12-alpine

lint:
  stage: build
  script:
    - npm i
    - npm run lint
  cache:
    policy: push
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npm i
    - npm run build
  cache:
    policy: push
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - npm i
    - npm run coverage
  cache:
    policy: pull
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/
      - coverage/

document:
  stage: test
  script:
    - npm i
    - npm run document
  cache:
    policy: pull
    paths:
      - node_modules/
  artifacts:
    paths:
      - doc/
